development:
  database: disaster_info2
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: disaster_info2_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db